apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-calculator-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ci-calculator
  template:
    metadata:
      labels:
        app: ci-calculator
    spec:
      containers:
        - name: ci-calculator
          image: yash5090/ci-calculator:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
