apiVersion: v1
kind: Service
metadata:
  name: ci-calculator-service
spec:
  selector:
    app: ci-calculator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
